#!/bin/sh
#
set -e

export EB_ROOT=$HOME/eb
export PATH=$EB_ROOT/bin:$PATH

mkdir -p $EB_ROOT/src
mkdir -p $EB_ROOT/bin
ln -s /usr/bin/python $EB_ROOT/bin
ln -s /Users/rpfische/macports/gcc49-python3/bin/gmd5sum $EB_ROOT/bin	# Needed to build a lua package.

cd $EB_ROOT/src
git clone --depth 1 -b 5.3.2 https://github.com/lua/lua.git
git clone --depth 1 -b 2.2.3 https://github.com/keplerproject/luarocks.git

#git clone --depth 1 -b 3.1.11 git://git.code.sf.net/p/lmod/code lmod-code
git clone --depth 1 -b 6.0.24 https://github.com/TACC/Lmod.git
#curl -O https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py

mkdir -p $EB_ROOT
cd $EB_ROOT
#git clone --depth 1 -b v2.3.x https://github.com/hpcugent/easybuild-easyconfigs
#ln -s easybuild-easyconfigs/easybuild/easyconfigs .

mkdir -p $EB_ROOT/git
cd $EB_ROOT/git
git clone https://github.com/hpcugent/vsc-base
git clone git@github.com:citibeth/easybuild-framework.git
git clone git@github.com:citibeth/easybuild-easyblocks.git
git clone git@github.com:citibeth/easybuild-easyconfigs.git



# --------------------------------------------------
# Get a Lua interpreter

# This will compile with system compiler.  We don't care, it
# doesn't need to interact with our library code.
cd $EB_ROOT/src/lua
sed -i.bak "s|/usr/local|$EB_ROOT|g" Makefile
# Compile with default compiler and settings for MacOSX
make macosx
make install


# Install Lua Rocks
cd $EB_ROOT/src/luarocks
./configure --prefix=$EB_ROOT
make build
make install
eval $(luarocks path --bin)

# Install prerequisites for llmod
luarocks install luaposix
eval $(luarocks path --bin)
luarocks install luafilesystem
eval $(luarocks path --bin)

# Install lmod
cd $EB_ROOT/src
cd Lmod
./configure --prefix=$EB_ROOT
make install
#ln -s $EB_ROOT/lmod/lmod/libexec $EB_ROOT/bin

# -----------------------------------------------
# EasyBuild


#cd $EB_ROOT/src
# PATH=$EB_ROOT/bin:$PATH 
#python bootstrap_eb.py $EB_ROOT		# Make sure "python" maps to system default python 2.7

# Help Python find the site directory (also see PYTHONUSERBASE)
#cd $EB_ROOT/software/EasyBuild/2.5.0/lib
#ln -s python2.7 python
